### ISSUE TITLE
Error "This class doesn't have any "kwargs" attribute! (VideoNode)"

### ISSUE THREAD

**Issue by MonoS** [Jaded-Encoding-Thaumaturgy/vs-scale#87]
When executing this simple script 
```
import vapoursynth as vs
import vsscale

core = vs.core

src = core.std.BlankClip(width=1920, height=1080, format=vs.YUV420P8)
res = vsscale.descale(src)

src.set_output()
```

The following error is returned

```
Failed to evaluate the script:
Python exception: This class doesn't have any "kwargs" attribute! (VideoNode)

Traceback (most recent call last):
File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
File "script.vpy", line 34, in 
res = vsscale.descale(src)
^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\vsscale\descale.py", line 314, in descale
descale_attempts = [
^
File "C:\Program Files\Python311\Lib\site-packages\vsscale\descale.py", line 315, in 
DescaleAttempt.from_args(
File "C:\Program Files\Python311\Lib\site-packages\vsscale\types.py", line 45, in from_args
descaled = kernel.descale(clip, width, height, shift)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 180, in _wrapper
return self.function(obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 310, in __call__
return self.__get__(None, self)(*args, **kwargs) # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 305, in _wrapper
return this.function(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\vskernels\kernels\complex.py", line 96, in func
return operation(clip, width, height, shift, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 180, in _wrapper
return self.function(obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 310, in __call__
return self.__get__(None, self)(*args, **kwargs) # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 305, in _wrapper
return this.function(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\vskernels\kernels\abstract.py", line 272, in descale
de_kwargs = self.get_descale_args(clip, shift, width, height // (1 + field_based.is_inter), **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\site-packages\stgpytools\types\utils.py", line 275, in _wrapper
raise CustomRuntimeError(
RuntimeError: This class doesn't have any "kwargs" attribute! (VideoNode)
```

All vs-jet packages were updated via vsjet latest

**Comment by NSQY** [comment]
update stgpytools

**Comment by MonoS** [comment]
> update stgpytools

already updated via latest git instruction
